;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ignore
	keyboard-escape-quit
	mouse-drag-mode-line
	mouse-minor-mode-menu
	mouse-select-window
	))

(setq mc/cmds-to-run-once
      '(
	handle-switch-frame
	mouse-set-region
	next-buffer
	previous-buffer
	))
